### ISSUE TITLE
Job submission is slow

### ISSUE THREAD

**Issue by dianaicd** [RomainFeron/snakemake-slurm#1]
Hello Romain, thanks for deploying this profile for axiom/wally!

We were using the profile in our group for some of our projects, but we've noticed that it is getting slow regarding job submission.

I followed the instructions to install the profile, and I launch my jobs as usual (i.e., `snakemake -s my_snakemake.smk --profile axiom`). Everything works as expected, except that the job submission is very slow.  For instance, a simple pipeline to touch 100 dummy files takes about 1 hour to be completed. 

This is a new behaviour we've noticed since a few weeks (probably months?). I was wondering if you've experienced the same issue and if you have any ideas of what could be slowing down the submission process.

Kind regards,
Diana

**Comment by RomainFeron** [comment]
Hi Diana,

I just tested the profile with this minimal example:

```python
rule test2:
    input: expand('test/{i}.txt', i=range(100))

rule test:
    output: 
        'test/{name}.txt'
    shell:
        'touch {output}'
```

I ran the command `snakemake --profile <axiom/wally>`. It took more than an hour on axiom (I stopped it early but it completed 10% in 10 minutes) and 3 minutes on wally.

I think the problem comes from axiom's file system which has been insanely slow for months now, but this specific issue with the profile is fairly recent (I did not use to have this problem back in August). I do not know exactly what is causing the lag though; interestingly, running `snakemake --cluster sbatch` is much faster, so the issue seems to be related to the profile itself. I will see if I can pinpoint the origin but it may not be fixable easily.

**Comment by RomainFeron** [comment]
I've tested a few things to understand where the lag is coming from. I first timed the steps of the submission process in the profile and it lasts a few seconds, so it's not fast but it's not causing the problem here. I then compared runtime for 1) `snakemake --cluster sbatch`, 2) the 'snakemake-slurm' profile, and 3) a fake profile with a very simple python submission script. Option 1 was much faster than 2 and 3 which had similar runtime. From the results it seems the bottleneck is executing a python script regardless of how complex the script is. I'm pretty sure this comes axiom being so slow overall, and I don't see an easy way to fix it.

In your case if you want to keep using axiom specifically you may want to try a very simple execution profile like this:

```yaml

jobs: 100
local-cores: 1
max-jobs-per-second: 5
max-status-checks-per-second: 10
cluster: sbatch --partition=axiom --cpus-per-task={threads} --mem={resources.mem} --runtime {resources.runtime}
restart-times: 3

```

Provided that you specified resources with the right format, this should work and be much faster than snakemake-slurm on axiom, but you would lose some of the features.

**Comment by dianaicd** [comment]
I see, thanks for having a look!
This workaround has vastly improved the submission process on my end 👍

**Comment by RomainFeron** [comment]
Glad I could help, I've mostly moved to wally myself because I couldn't handle axiom's slugginess
